# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: |
        (?x)^(
            .*/tests/fixtures/.*
        )$
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo-fmt
    description: Format files with cargo fmt.
    entry: cargo fmt
    language: rust
    types: [rust]
    args: ["--"]
  - id: cargo-fix
    name: cargo-fix
    description: Run cargo fix on the codebase.
    entry: cargo fix
    language: rust
    types: [rust]
    pass_filenames: false
    args: ["--allow-dirty", "--allow-staged"]
