name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: cache rust
      uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo test --verbose

  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install rust stable
      uses: dtolnay/rust-toolchain@stable
    - name: cache rust
      uses: Swatinem/rust-cache@v2
    - name: Package crates
      run: cargo package --workspace
